name: PR Comment CI/CD Start

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment-pr:
    name: Comentar inicio del pipeline
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Comentar en el PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: "CI/CD en acción. Ejecutando tareas …"
